@host=http://localhost:5039

POST {{host}}/auth/register
Content-Type:  application/json

{
    "firstName":"Jullian",
    "lastName":"Christopher",
    "email":"",
    "password":"helloWolrd123*"
}

###

