@host=http://localhost:5039

GET {{host}}/Dinners/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTgxMTM5Yy00MDY1LTQzNWUtYmRjNS1iZWJiOGY2ZDZiZDgiLCJqdGkiOiJiYzhkOTlkZC0zNzk0LTQ1NDMtOGQ5Yi00M2I1MTE1OGY3M2QiLCJnaXZlbl9uYW1lIjoiSnVsbGlhbiIsImZhbWlseV9uYW1lIjoiQ2hyaXN0b3BoZXIiLCJleHAiOjE3MDg2ODk2MTEsImlzcyI6IkpSZXN0YXVyYW50IiwiYXVkIjoiSlJlc3RhdXJhbnQifQ.dS06J3J0z3MF49fd3W82aXl5LzhECX5vLeeHQW257o8
Content-Type:  application/json
